POST http://localhost:3000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUzNWI1ZmZjLTYzMTgtNDYwNy1hMGNiLWVmYTExNDQ3MGE0OCIsImlhdCI6MTU4MTQ2Mjc0NiwiZXhwIjoxNTgxNDY2MzQ2fQ.5-L6NAOy1F8LbMmaF2nayKSYxZxrdvqGnGBnxdnj1b0

{
  "firstName": "Bogdan",
  "lastName": "Matei",
  "email": "bogdan@matei.dev",
  "username": "bogdan",
  "password": "password"
}

###
